# Generated by Django 6.0.4 on 2026-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(blank=True, help_text='Highest qualification (e.g., B.Tech, MCA)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Company phone number for WhatsApp/call', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Customer Support, Python Developer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(help_text='Current city/location', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(help_text='Comma-separated skills (e.g., Python, Django, React)'),
        ),
    ]
