# Generated by Django 6.0.4 on 2026-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0002_candidateprofile_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide job from dashboard'),
        ),
    ]
